<?php

/**
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please contact us
 * via http://www.fia-net-group.com/formulaire.php so we can send you a copy immediately.
 *
 * @author     FIA-NET <support-boutique@fia-net.com>
 * @copyright  Copyright (c) 2017 FIA-NET
 * @version    Release: $Revision: 0.1.0 $
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<?php
/** @var Fianet_Payment3xcb_Block_Payment_Info $this */
echo $this->getMethod()->getTitle();

/** @var Mage_Sales_Model_Order $order */
$order = $this->getParentBlock()->getParentBlock()->getOrder();

/** @var Mage_Core_Model_Layout $layout */
$layout = Mage::getSingleton('core/layout');

/** @var Fianet_Payment3xcb_Block_TransactionState $block */
$block = $layout->createBlock('fianetpayment3xcb/transactionState');
$block->setState($order->getFianet3xcbState())
    ->setMode($order->getFianet3xcbMode());
?>
<div style="float:right">
    <?php echo $block->toHtml(); ?>
</div>
