<?php

/**
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please contact us
 * via http://www.fia-net-group.com/formulaire.php so we can send you a copy immediately.
 *
 * @author     FIA-NET <support-boutique@fia-net.com>
 * @copyright  Copyright (c) 2017 FIA-NET
 * @version    Release: $Revision: 0.1.0 $
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<div id="category-edit-container" class="category-content">
    <?php echo $this->getFormInitScripts() ?>
    <div class="content-header">
        <?php echo $this->getHeaderHtml() ?>
        <p class="content-buttons form-buttons"><?php echo $this->getButtonsHtml('header') ?></p>
    </div>

    <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="edit_form">
        <?php echo $this->getChildHtml('form') ?>
    </form>

    <?php if ($this->hasFooterButtons()): ?>
        <div class="content-footer">
            <p class="content-buttons form-buttons"><?php echo $this->getButtonsHtml('footer') ?></p>
        </div>
    <?php endif; ?>
    <script type="text/javascript">
        var editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl() ?>');
    </script>
    <!-- TODO: avoid error -->
        <div id="add_subcategory_button"></div>
    <!-- -->
    <?php echo $this->getFormScripts() ?>
    <?php echo $this->getChildHtml('googleoptimizer_js') ?>
</div>
