<?php

/**
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please contact us
 * via http://www.fia-net-group.com/formulaire.php so we can send you a copy immediately.
 *
 * @author     FIA-NET <support-boutique@fia-net.com>
 * @copyright  Copyright (c) 2017 FIA-NET
 * @version    Release: $Revision: 0.1.0 $
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>

<p><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></p>
<p>
    <img width="116" height="159" style="padding:15px"
        src="<?php echo $this->getSkinUrl('images/fianetpayment3xcb/3xcb_logo.png'); ?>"
        alt="<?php echo $this->escapeHtml($this->__('FIA-NET 3xCB - Payment in 2, 3 or 4 times by credit card')); ?>"/>
</p>
<?php if ($this->isTestMode()): ?>
    <div id="messages">
        <ul class="messages">
            <li class="error-msg">
                <ul>
                    <li><?php echo $this->__('This payment method is currently in test phase, no payment possible.'); ?></li>
                </ul>
            </li>
        </ul>
    </div>
<?php endif; ?>
